#pragma once

#define ARBA_APPT_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define ARBA_APPT_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define ARBA_APPT_VERSION_PATCH @PROJECT_VERSION_PATCH@
#define ARBA_APPT_VERSION "@PROJECT_VERSION@"
